baseURL = "https://kevlut.github.io"
languageCode = "en-us"
title = "Kevin Luty"
theme = "osprey"
config = "config.toml"
canonifyURLS = true

[Params]
    tagline = "Kevin C. Luty"
    author = "Kevin Kevin"
    description = "Software Engineer based out of Milwaukee, WI"
    #logoBig = "/images/osprey-logo.png"
    #logoSmall = "/images/osprey-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = "KevinLutyBlogs"
    linkedin = "kevin-luty-586bb521"
    github = "kevlut"
    email = ""
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
